const CreditPayments = {
    BEST_BUY: 'BEST BUY AUTO PYMT',
    AMAZON_CC_PAYMENT: 'AMZ_STORECRD_PMT',
    AFFIRM: 'AFFIRM',
    AFFIRM_PELOTON: 'AFF Peloton',
    APPLE_CARD: 'APPLECARD GSBANK PAYMENT',
    CAP_CC_PAYMENT: 'CAPITAL ONE CRCARDPMT',
    OLD_NAVY: 'BARCLAYCARD US CREDITCARD',
    CITI: 'CITI AUTOPAY PAYMENT',
    KLARNA: 'KLARNA',
}

export default CreditPayments

